### ISSUE TITLE
Clean up the repo - NLP-Experiments-with-Judicial-Data

### ISSUE THREAD

**Issue by apoorv74** [CivicDataLab/NLP-Experiments-with-Judicial-Data#1]
@d-saikrishna - We need to clean this up a bit. Noting down a few issues:

- Rename the files/folders/sub-folders within the repo. Instead of `Assam`, let's have a folder called `Judgments` or `Data` and then have files within that folder
- Rename the repo - A more intuitive name in line with the experiment
- Confirm the license to be used here. CC-BY might not be relevant. Check with @Deepthi-Chand
- Check the completeness of analysis notebooks. I see some empty blocks, etc. Please make sure that it is well documented.
- Explain the directory structure in the README file
- Explain how to run this analysis in the README file. Be as detailed as possible.

**Comment by d-saikrishna** [comment]
@apoorv74 please check now. 

A few empty blocks in the code are when there is an extremely time taking code (PDF-to-Txt conversion) - which I cannot run now to show results. I have included text wherever I can in the form of comments and markdowns. 

Changed the license to AGPL License as per @Deepthi-Chand's advice. 

Changed the name of the Repo to "NLP Experiments with Judicial Data"

**Comment by apoorv74** [comment]
Remove the judgements from the repo before making it public @d-saikrishna

**Comment by d-saikrishna** [comment]
Yes, removed the judgments and cleaned the repo accordingly. Please review @apoorv74

**Comment by apoorv74** [comment]
@d-saikrishna moved this repo here - https://github.com/justicehub-in/NLP_Experiments
